### PR TITLE
Added LiveQuery Options

### PR DESCRIPTION
**Pull request by AliabbasMerchant**
@YourTechBud I have added an example in `docs/LiveQuery.java`

### CODE REVIEW

**Comment by AliabbasMerchant** [comment]
@YourTechBud Done

**Comment by YourTechBud** [comment]
@AliabbasMerchant shouldn't onSnapshot take 3 parameters now. The first is the array of docs (this will be an empty array when changesOnly is true). Second is the kind / type of change. Third is the doc(s) which changed.

**Comment by AliabbasMerchant** [comment]
I have kept them the same. Even in Python.  
If `changesOnly` is false, it works the same.  
If it is true, it calls `onSnapshot` with the individual changes(in List, so as not to cause any inconsistencies) as the docs. And second parameter as the type of change

**Comment by YourTechBud** [comment]
@AliabbasMerchant we will need three parameters. Often we need to check what has changed even when changeOnly is false

**Comment by AliabbasMerchant** [comment]
So when changeOnly is false, even then do we send the changed items?

**Comment by YourTechBud** [comment]
We send all three all the time. Changed items is passed irrespective of the value of changeOnly. Docs will always be an empty array when changeOnly is true.

**Pull request merged**
